using UnityEngine;

namespace Grid {
    public class GridSystemVisualSingle : MonoBehaviour {
        [SerializeField] private MeshRenderer meshRenderer;
        // [SerializeField] private GameObject selectedGameObject;

        public void Show(Material material) {
            meshRenderer.material = material;
            meshRenderer.enabled = true;
        }

        public void Hide() => meshRenderer.enabled = false;

        // public void SetSelected(bool selected) => selectedGameObject.SetActive(selected);
    }
}